import * as cheerio from "cheerio";
import { scrapeRoutineWithPlaywright, scrapeRoutineDynamicHttp } from "./scraper";

export interface RoutineSlot {
  subject: string;
  teacher: string;
  room: string;
  startTime: string;
  endTime: string;
  colspan: number;
}

export interface DaySchedule {
  day: string;
  slots: RoutineSlot[];
}

export interface GroupRoutine {
  group: string;
  schedule: DaySchedule[];
}

export interface ApiResponse extends GroupRoutine {
  groups: string[];
}

function normalizeTime(t: string): string {
  const parts = t.trim().split(":");
  if (parts.length === 2) {
    return `${parts[0].padStart(2, "0")}:${parts[1].padStart(2, "0")}`;
  }
  return t.trim();
}

/**
 * Dynamically navigates and retrieves the routine HTML (using Playwright or dynamic crawler),
 * then parses all routine tables using Cheerio.
 */
export async function fetchAndParseAllRoutines(groupName?: string): Promise<{
  allRoutines: Map<string, GroupRoutine>;
  groups: string[];
}> {
  let html: string;
  try {
    // Attempt headless browser extraction (or dynamic fallback if browser not installed)
    html = await scrapeRoutineWithPlaywright(groupName);
  } catch (err) {
    console.warn("Playwright execution error, trying dynamic HTTP fetching:", err);
    html = await scrapeRoutineDynamicHttp();
  }

  return parseRoutineHtml(html);
}

/**
 * Parses raw HTML table structures generated by FET / university portal into structured JSON.
 */
export function parseRoutineHtml(html: string): {
  allRoutines: Map<string, GroupRoutine>;
  groups: string[];
} {
  const $ = cheerio.load(html);
  const allRoutines = new Map<string, GroupRoutine>();
  const groups: string[] = [];

  $("table[border='1'], table.odd_table, table.even_table").each((_, table) => {
    const $table = $(table);
    const caption = $table.find("caption");
    if (!caption.length) return;

    let groupName = caption.find(".name").text().trim();
    if (!groupName) {
      const fullCaption = caption.text().trim();
      const parts = fullCaption.split("\n").map((p) => p.trim()).filter(Boolean);
      groupName = parts.length > 1 ? parts[parts.length - 1] : fullCaption;
    }

    if (!groupName) return;

    // Parse time headers
    const timeSlots: { start: string; end: string }[] = [];
    $table.find("thead tr th.xAxis").each((_, th) => {
      const text = $(th).text().trim();
      const [start, end] = text.split("-");
      if (start && end) {
        timeSlots.push({
          start: normalizeTime(start),
          end: normalizeTime(end),
        });
      }
    });

    if (timeSlots.length === 0) return;

    const schedule: DaySchedule[] = [];

    $table.find("tbody tr").each((_, tr) => {
      const $tr = $(tr);
      if ($tr.hasClass("foot")) return;

      const dayHeader = $tr.find("th.yAxis").text().trim();
      if (!dayHeader) return;

      const daySlots: RoutineSlot[] = [];
      let currentSlotIndex = 0;

      $tr.find("td").each((_, td) => {
        const $td = $(td);
        const colspanAttr = $td.attr("colspan");
        const colspan = colspanAttr ? parseInt(colspanAttr, 10) : 1;

        const isNotAvailable = $td.hasClass("notAvailable") || $td.find(".notAvailable").length > 0;
        const isEmpty = $td.hasClass("empty") || $td.find(".empty").length > 0;
        const textContent = $td.text().trim();

        if (
          !isNotAvailable &&
          !isEmpty &&
          textContent !== "-x-" &&
          textContent !== "---" &&
          textContent !== ""
        ) {
          const subject =
            $td.find(".subject").text().trim() ||
            $td.find(".line1 span").text().trim() ||
            $td.find(".line1").text().trim() ||
            $td.find("div:nth-child(1)").text().trim();

          const teacher =
            $td.find(".teacher").text().trim() ||
            $td.find(".line2").text().trim() ||
            $td.find("div:nth-child(2)").text().trim();

          const room =
            $td.find(".room").text().trim() ||
            $td.find(".line3").text().trim() ||
            $td.find("div:nth-child(3)").text().trim();

          const startIdx = currentSlotIndex;
          const endIdx = Math.min(currentSlotIndex + colspan - 1, timeSlots.length - 1);

          const startTime =
            startIdx < timeSlots.length ? timeSlots[startIdx].start : "00:00";
          const endTime =
            endIdx < timeSlots.length ? timeSlots[endIdx].end : "00:00";

          if (subject) {
            daySlots.push({
              subject,
              teacher,
              room,
              startTime,
              endTime,
              colspan,
            });
          }
        }

        currentSlotIndex += colspan;
      });

      schedule.push({
        day: dayHeader,
        slots: daySlots,
      });
    });

    if (!allRoutines.has(groupName)) {
      groups.push(groupName);
      allRoutines.set(groupName, {
        group: groupName,
        schedule,
      });
    }
  });

  return { allRoutines, groups };
}
